### ISSUE TITLE
Can't use it with TS

### ISSUE THREAD

**Issue by IvanCoronado** [mohitgupta8888/react-currency-format#1]
I am importing it as `import * as CurrencyFormat  from 'react-currency-format';` but still getting next error:

![image](https://user-images.githubusercontent.com/13351933/40776497-2bf725ca-64cb-11e8-9f61-1eed0b2944bd.png)

**Comment by IvanCoronado** [comment]
workaround with `const CurrencyFormat: any = require('react-currency-format');`

**Comment by mohitgupta8888** [comment]
This package is not written in typescript and types are not defined. There are workarounds available to use this with typescript.
Thanks @IvanCoronado for sharing the workaround. Closing the issue.

**Comment by lancesnider** [comment]
Just add the types package and it'll work fine: 

```
npm install --save @types/react-currency-format

// for yarn
yarn add @types/react-currency-format
```
