### ISSUE TITLE
This package is still on version 1.0.0 on NPM and therefore doesn't support React 17+

### ISSUE THREAD

**Issue by daveidivide** [mohitgupta8888/react-currency-format#24]
Please push the latest changes to NPM.

Version 1.0.0 is still the latest here: [https://www.npmjs.com/package/react-currency-format](https://www.npmjs.com/package/react-currency-format)

Anyone trying to use this package with React 17+ and has NPM 7+ will fail install and receive the following error:

`Could not resolve dependency:
npm ERR! peer react@"^0.14 || ^15.0.0-rc || ^15.0.0 || ^16.0.0-rc || ^16.0.0" from react-currency-format@1.0.0`

**Comment by mbyrne00** [comment]
Dead lib ... swap out for[ react-number-format](https://github.com/s-yadav/react-number-format#readme).

**Comment by kesava-karri** [comment]
I have had the same issue.

**Comment by kesava-karri** [comment]
> Please push the latest changes to NPM.
> 
> Version 1.0.0 is still the latest here: https://www.npmjs.com/package/react-currency-format
> 
> Anyone trying to use this package with React 17+ and has NPM 7+ will fail install and receive the following error:
> 
> `Could not resolve dependency: npm ERR! peer react@"^0.14 || ^15.0.0-rc || ^15.0.0 || ^16.0.0-rc || ^16.0.0" from react-currency-format@1.0.0`

I have had the same issue.

**Comment by mohitgupta8888** [comment]
Fixed.
